### ISSUE TITLE
Failed to activate the atoms-touchbar package

### ISSUE THREAD

**Issue by ryanapil** [sean-codes/atoms-touchbar#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atoms-touchbar](https://github.com/sean-codes/atoms-touchbar) package 0.4.0

### Stack Trace

Failed to activate the atoms-touchbar package

```
At Cannot read property 'setTouchBar' of null

TypeError: Cannot read property 'setTouchBar' of null
    at AtomTouchbarView.render (/packages/atoms-touchbar/lib/atom-touchbar-view.js:45:39)
    at AtomTouchbarView.changeTouchBar (/packages/atoms-touchbar/lib/atom-touchbar-view.js:36:12)
    at /packages/atoms-touchbar/lib/atom-touchbar-view.js:32:12)
    at Object.activate (/packages/atoms-touchbar/lib/atom-touchbar.js:9:31)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -1:32.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:18.5.0 core:paste (input.hidden-input)
  2x -1:17.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atoms-touchbar 0.4.0 
busy-signal 1.4.3 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-stylelint 4.0.1 
linter-tidy 2.3.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
pigments 0.39.1 
sync-settings 0.8.2 
```

**Comment by yangwao** [comment]
bump, I tried use it, but this happend to me.

**Comment by hassanzouhar** [comment]
bump, same here.
